runtime: python37
# threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: auto

# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK
# Using Third Party Libraries: https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27
# libraries:
# - name: mysqlclient
#   version: 1.3.13
